[profile.default]
solc-version = '0.8.20'
src = 'contracts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache/foundry'
verbosity = 3
optimize = true
optimizer_runs = 200
libs = [
    'lib',
    'node_modules',
]

remappings = [
    'forge-std/=lib/forge-std/src/',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

[fuzz]
runs = 1000